name: test action

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install pkg
      run: |
        # pip install -r requirements.txt
        pip install bibtexparser
        pip install matplotlib requests IPython pytest
    - name: Run tests
      run: |
        python -m pytest    
